server:
  port: 10000
spring:
  application:
    name: pdf #应用名字
  jackson:
    date-format: yyyy‐MM‐dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 120.27.63.0
    password: bd9d78
    port: 6379
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10000MB
      # 设置总上传的文件大小
      max-request-size: 20000MB


