server:
  port: 10000
spring:
  application:
    name: mp #应用名字
  jackson:
    date-format: yyyy‐MM‐dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 120.27.63.0
    password: bd9d78
    port: 6379


