server:
  port: 10000
logging:
  #在Spring Boot项目中默认加载类路径下的logback-spring.xml文件
  config: classpath:logback-spring.xml
spring:
  application:
    name: aspectj #应用名字
  jackson:
    date-format: yyyy‐MM‐dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

