server:
  port: 10001
spring:
  application:
    name: sharding #应用名字
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy‐MM‐dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  redis:
    database: 0
    host: 120.27.63.0
    password: bd9d78
    port: 6379
  datasource:
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        #监控统计拦截的filters
        filters: stat
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
      primary: edudata
      strict: false
      datasource:
        edudata:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://120.27.63.0:3306/edudata?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true
          username: root
          password: 35f3eac33f6f79db
          type: com.alibaba.druid.pool.DruidDataSource
        edudata2019:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://120.27.63.0:3306/edudata2019?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true
          username: root
          password: 35f3eac33f6f79db
          type: com.alibaba.druid.pool.DruidDataSource
        edudata2020:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://120.27.63.0:3306/edudata2020?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true
          username: root
          password: 35f3eac33f6f79db
          type: com.alibaba.druid.pool.DruidDataSource
        edudata2021:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://120.27.63.0:3306/edudata2021?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true
          username: root
          password: 35f3eac33f6f79db
          type: com.alibaba.druid.pool.DruidDataSource

jwt:
  secret: 123312322132112621


